Repository openshift/kubernetes-client-go, pull requests merged in 2020-03, with the labels that each got.

#11 Bug 1812593: Live reload kubeconfig certs
  rest/request.go
  transport/cache.go
  transport/cert_rotation.go
  transport/config.go
  transport/transport.go
Labels: bugzilla/invalid-bug, size/L

#10 Base client-go branch for 1.18.0-beta.2
  tools/clientcmd/config.go
  tools/clientcmd/loader.go
  tools/clientcmd/loader_test.go
Labels: approved, lgtm, size/M

#12 Base client-go branch for 1.18.0
  tools/clientcmd/config.go
  tools/clientcmd/loader.go
  tools/clientcmd/loader_test.go
Labels: approved, lgtm
